/**
 * Emoji kataloğu — seçicide gösterilen, tüm kullanıcılara ortak liste.
 * Görseller Microsoft Fluent Emoji 3D (MIT) setinden, 128px PNG olarak
 * `assets/emoji/<code>.png` altında ve `/api/static/emoji/` adresinden sunulur.
 *
 * Kayıtlarda emoji Unicode karakter olarak saklanır (`emoji: "😊"`); `code`
 * yalnızca görsel dosyasının adıdır: FE0F'siz kod noktaları, '-' ile birleşik.
 * Emoji eklemek için: görseli assets/emoji'ye koy, buraya kaydını ekle.
 *
 * Bu dosya bir kez üretildi (Fluent metadata + Unicode CLDR Türkçe adları);
 * artık elle düzenlenir.
 */

export interface EmojiEntry {
  emoji: string;
  code: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  emojis: EmojiEntry[];
}

/** Katalog değiştikçe artır — istemci önbelleğini tazeler. */
export const EMOJI_CATALOG_VERSION = '7a34d995';

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'faces',
    name: 'Yüzler',
    emojis: [
      {
        emoji: '😀',
        code: '1f600',
        name: 'sırıtan yüz',
        keywords: ['gülen yüz', 'gülme', 'keyifli', 'lol', 'mutlu', 'neşeli'],
      },
      {
        emoji: '😃',
        code: '1f603',
        name: 'ağzı açık sırıtma',
        keywords: [
          'ağzı açık gülen yüz',
          'ağzı açık gülümseme',
          'gülen yüz',
          'gülme',
          'gülümseme',
          'lol',
        ],
      },
      {
        emoji: '😄',
        code: '1f604',
        name: 'gülen gözlerle ağzı açık sırıtma',
        keywords: [
          'ağzı açık gülen gözler',
          'gülen gözlerle ağzı açık gülümseme',
          'gülen yüz',
          'gülme',
          'gülümseme',
          'lol',
        ],
      },
      {
        emoji: '😁',
        code: '1f601',
        name: 'gülen gözlerle sırıtma',
        keywords: [
          'gülen gözlerle sırıtan yüz',
          'gülen yüz',
          'gülme',
          'gülümseme',
          'gülümseyen gözler',
          'lol',
        ],
      },
      {
        emoji: '😆',
        code: '1f606',
        name: 'kapalı gözlerle ağzı açık sırıtma',
        keywords: ['32 diş', 'ağız', 'ahaha', 'çok komik', 'gözler kapalı', 'gülmek'],
      },
      {
        emoji: '😅',
        code: '1f605',
        name: 'soğuk terli ağzı açık gülümseme',
        keywords: ['heyecanlı', 'soğuk ter', 'stresli', 'yüz'],
      },
      {
        emoji: '🤣',
        code: '1f923',
        name: 'gülmekten yerlere yatma',
        keywords: ['ahaha', 'çok komik', 'gözümden yaş geldi', 'gözyaşı', 'gülme', 'hahaha'],
      },
      {
        emoji: '😂',
        code: '1f602',
        name: 'sevinç gözyaşları',
        keywords: ['ağlamak', 'gözyaşı', 'gülmek', 'gülmekten ağlamak', 'haha', 'inanılmaz'],
      },
      {
        emoji: '🙂',
        code: '1f642',
        name: 'hafifçe gülümseyen yüz',
        keywords: ['gülme', 'gülümseme', 'hafifçe gülümseme', 'mutlu', 'neşeli', 'yüz'],
      },
      {
        emoji: '🙃',
        code: '1f643',
        name: 'ters yüz',
        keywords: ['gülme', 'gülümseme', 'hehe', 'yüz'],
      },
      {
        emoji: '🫠',
        code: '1fae0',
        name: 'eriyen yüz',
        keywords: ['aşkından erimek', 'çözülme', 'eridim', 'erime', 'eriyorum', 'ifade'],
      },
      {
        emoji: '😉',
        code: '1f609',
        name: 'göz kırpan yüz',
        keywords: ['cilve', 'göz kırpma', 'yüz'],
      },
      {
        emoji: '😊',
        code: '1f60a',
        name: 'ağzı açık gülme',
        keywords: [
          'gülen gözlerle gülümseme',
          'gülümseyen gözler',
          'gülümseyen yüz',
          'gülümseyen yüz ve gözler',
          'samimi',
          'sevecen',
        ],
      },
      {
        emoji: '😇',
        code: '1f607',
        name: 'ışık halkalı gülümseme',
        keywords: ['gülümseme', 'hare', 'ışık halkası', 'melek', 'yüz'],
      },
      {
        emoji: '🥰',
        code: '1f970',
        name: '3 kalpli gülümseyen yüz',
        keywords: ['aşık', 'aşk', 'çarpılma', 'gülen yüz', 'hayranlık', 'ilk görüşte aşk'],
      },
      {
        emoji: '😍',
        code: '1f60d',
        name: 'kalp gözlü gülümseme',
        keywords: ['aşk', 'değer verme', 'gözler', 'kalp', 'kalpler', 'romantik'],
      },
      {
        emoji: '🤩',
        code: '1f929',
        name: 'yıldız çarpmış',
        keywords: ['gözler', 'heyecanlı', 'sırıtan', 'surat', 'vov', 'yıldız'],
      },
      {
        emoji: '😘',
        code: '1f618',
        name: 'öpücük gönderen yüz',
        keywords: ['aşk', 'muah', 'muck', 'öptüm', 'romantik', 'sevgi'],
      },
      {
        emoji: '😗',
        code: '1f617',
        name: 'öpen yüz',
        keywords: ['aşk', 'cilve', 'muah', 'muck', 'öpücük', 'sevgi'],
      },
      {
        emoji: '☺️',
        code: '263a',
        name: 'gülen yüz',
        keywords: ['içi boş gülen yüz', 'masum', 'mutlu', 'utandım', 'utanmış', 'yüz'],
      },
      {
        emoji: '😚',
        code: '1f61a',
        name: 'kapalı gözlerle öpen yüz',
        keywords: ['aşk', 'gözler kapalı', 'gözler kapalı öpüşme', 'öpücük yollama', 'yüz'],
      },
      {
        emoji: '😙',
        code: '1f619',
        name: 'gülen gözlerle öpen yüz',
        keywords: [
          'gülümseme',
          'gülümseyen gözler',
          'gülümseyerek öpen yüz',
          'öptüm',
          'öpücük',
          'yüz',
        ],
      },
      {
        emoji: '🥲',
        code: '1f972',
        name: 'gözü yaşlı gülümseyen yüz',
        keywords: ['acı', 'duygulanmış', 'gözyaşı', 'gülümseme', 'gururlu', 'hislenmiş'],
      },
      {
        emoji: '😋',
        code: '1f60b',
        name: 'lezzetli yiyecek beğenen yüz',
        keywords: [
          'gülümseyen yüz',
          'harika yemek',
          'keyifli yemek',
          'lezzetli',
          'oh oh harika',
          'yüz',
        ],
      },
      {
        emoji: '😛',
        code: '1f61b',
        name: 'dil dışarıda',
        keywords: ['dil çıkarmış yüz', 'dil dışarıda kalmış', 'komik', 'şapşal', 'yüz'],
      },
      {
        emoji: '😜',
        code: '1f61c',
        name: 'dili dışarda göz kırpma',
        keywords: [
          'dil dışardayken göz kırpma',
          'göz kırpma',
          'haylaz',
          'kışkırtma',
          'şaka',
          'yaramaz',
        ],
      },
      {
        emoji: '🤪',
        code: '1f92a',
        name: 'çılgın surat',
        keywords: ['büyük', 'çılgın', 'deli', 'göz', 'gözler', 'küçük'],
      },
      {
        emoji: '😝',
        code: '1f61d',
        name: 'dil dışarıda ve gözler kapalı',
        keywords: [
          'dil dışarıda',
          'gözler kapalı',
          'gözler kapalı ve dil dışarıda',
          'iğrenç',
          'korkunç',
          'öğk',
        ],
      },
      {
        emoji: '🤑',
        code: '1f911',
        name: 'para ağızlı yüz',
        keywords: ['ağız', 'gözünü para bürümüş', 'para', 'para göz', 'yüz'],
      },
      {
        emoji: '🤗',
        code: '1f917',
        name: 'kucaklayarak gülümseme',
        keywords: ['heyecanlı', 'kucaklama', 'sarılma', 'yüz'],
      },
      {
        emoji: '🤭',
        code: '1f92d',
        name: 'eliyle ağzını kapatan yüz',
        keywords: ['a ah', 'sır', 'şok olmak', 'süpriz', 'surat', 'tüh'],
      },
      {
        emoji: '🫢',
        code: '1fae2',
        name: 'gözleri açık ve eliyle ağzını kapatan yüz',
        keywords: ['hayret', 'ifade', 'inanamama', 'inanılmaz', 'korku', 'şaşkınlık'],
      },
      {
        emoji: '🤫',
        code: '1f92b',
        name: 'sus işareti yapan yüz',
        keywords: ['sessiz', 'şişt', 'şş', 'surat'],
      },
      {
        emoji: '🤔',
        code: '1f914',
        name: 'düşünen yüz',
        keywords: ['düşünme', 'yüz'],
      },
      {
        emoji: '🫡',
        code: '1fae1',
        name: 'selamlayan yüz',
        keywords: ['anlaştık', 'asker', 'başüstüne', 'emredersiniz', 'güneşli', 'ifade'],
      },
      {
        emoji: '🤐',
        code: '1f910',
        name: 'ağzı fermuarlı yüz',
        keywords: ['ağız', 'ağzı fermuarlı', 'ağzım kapalı', 'fermuar', 'sır', 'yüz'],
      },
      {
        emoji: '🤨',
        code: '1f928',
        name: 'tek kaşı çatık yüz',
        keywords: ['güvenmeyen', 'şüpheci', 'surat', 'tek kaşı havada'],
      },
      {
        emoji: '😐',
        code: '1f610',
        name: 'duygusuz yüz',
        keywords: ['duygusuz', 'etkilenmemiş', 'nötr', 'umurumda değil', 'yorum yok', 'yüz'],
      },
      {
        emoji: '😑',
        code: '1f611',
        name: 'ifadesiz yüz',
        keywords: ['ifadesizlik', 'kıskanç', 'umurumda değil', 'yorum yok', 'yüz'],
      },
      {
        emoji: '😶',
        code: '1f636',
        name: 'ağzı olmayan yüz',
        keywords: ['ağız', 'ifadesiz', 'sakin', 'sesi kesilmiş', 'sessiz', 'sır'],
      },
      {
        emoji: '😏',
        code: '1f60f',
        name: 'imalı gülümseme',
        keywords: [
          'hin',
          'kuşkucu',
          'sinsi',
          'yapmacık gülümseme',
          'yapmacık gülümseyen',
          'yapmacık gülümseyen yüz',
        ],
      },
      {
        emoji: '😒',
        code: '1f612',
        name: 'keyifsiz yüz',
        keywords: ['canı sıkkın', 'canım sıkıldı', 'garip', 'keyifsiz', 'mutsuz', 'neyse'],
      },
      {
        emoji: '🙄',
        code: '1f644',
        name: 'gözlerini deviren yüz',
        keywords: [
          'bana ne',
          'banane',
          'beni ilgilendirmez',
          'bilemiyorum',
          'göz devirme',
          'her neyse',
        ],
      },
      {
        emoji: '😬',
        code: '1f62c',
        name: 'dişlerini gösteren yüz',
        keywords: ['dişçi', 'dişlerini sıkmak', 'endişeli', 'tedirgin', 'yüz', 'yüzünü ekşitme'],
      },
      {
        emoji: '😮‍💨',
        code: '1f62e-200d-1f4a8',
        name: 'nefes veren yüz',
        keywords: ['bitik', 'duman', 'fısıldama', 'iç çekme', 'ıslık', 'nefes verme'],
      },
      {
        emoji: '🤥',
        code: '1f925',
        name: 'yalan söyleyen yüz',
        keywords: ['pinokyo', 'yalan söyleme', 'yüz'],
      },
      {
        emoji: '😌',
        code: '1f60c',
        name: 'rahatlamış yüz',
        keywords: ['huzur', 'rahatlamış', 'yüz'],
      },
      {
        emoji: '😔',
        code: '1f614',
        name: 'düşünceli yüz',
        keywords: ['dargın', 'düşünceli', 'gemileri batmış', 'karamsar', 'üzgün', 'yüz'],
      },
      {
        emoji: '😪',
        code: '1f62a',
        name: 'uykulu yüz',
        keywords: ['ağlayan yüz', 'yorgun', 'yüz'],
      },
      {
        emoji: '🤤',
        code: '1f924',
        name: 'salya akıtan yüz',
        keywords: ['ağzı sulanmış', 'salya akıtma', 'yüz'],
      },
      {
        emoji: '😴',
        code: '1f634',
        name: 'uyuyan yüz',
        keywords: ['esnemek', 'iyi geceler', 'iyi uykular', 'şekerleme', 'tatlı rüyalar', 'uyku'],
      },
      {
        emoji: '😷',
        code: '1f637',
        name: 'maskeli yüz',
        keywords: ['grip', 'hasta', 'maske', 'nezle', 'rahatsız', 'soğuk'],
      },
      {
        emoji: '🤒',
        code: '1f912',
        name: 'ağzında termometre olan yüz',
        keywords: ['ateş', 'grip', 'hasta', 'nezle', 'termometre', 'yüz'],
      },
      {
        emoji: '🤕',
        code: '1f915',
        name: 'kafası sarılı yüz',
        keywords: ['bandaj', 'yara', 'yaralı', 'yüz'],
      },
      {
        emoji: '🤢',
        code: '1f922',
        name: 'kusmak üzere olan yüz',
        keywords: ['iğrenç', 'istifra', 'kusmak üzere', 'midesi bulanmış', 'yüz'],
      },
      {
        emoji: '🤮',
        code: '1f92e',
        name: 'kusan yüz',
        keywords: ['hasta', 'istifra', 'kusmak', 'kusmuk', 'surat'],
      },
      {
        emoji: '🤧',
        code: '1f927',
        name: 'hapşıran yüz',
        keywords: ['çok yaşa', 'grip', 'hapşırma', 'hasta', 'nezle', 'yüz'],
      },
      {
        emoji: '🥵',
        code: '1f975',
        name: 'kızarmış yüz',
        keywords: ['ateşlenmek', 'çarpıntı', 'hararet', 'nefes nefese', 'sıcak', 'sıcak çarpması'],
      },
      {
        emoji: '🥶',
        code: '1f976',
        name: 'üşümüş yüz',
        keywords: ['buz', 'buz gibi', 'buz kesme', 'donma', 'kış', 'mavi surat'],
      },
      {
        emoji: '🥴',
        code: '1f974',
        name: 'sarhoş yüz',
        keywords: [
          'akşamdan kalma',
          'alkollü',
          'baş dönmesi',
          'çakırkeyif',
          'kaymış gözler',
          'sarhoş',
        ],
      },
      {
        emoji: '😵',
        code: '1f635',
        name: 'sersemlemiş yüz',
        keywords: ['başı dönen', 'baygınlık', 'hasta', 'sersemlemiş', 'yüz'],
      },
      {
        emoji: '😵‍💫',
        code: '1f635-200d-1f4ab',
        name: 'sarmal gözlü yüz',
        keywords: [
          'aklı karışık',
          'aman tanrım',
          'başım döndü',
          'gülen yüz',
          'hipnotize',
          'inanamıyorum',
        ],
      },
      {
        emoji: '🤯',
        code: '1f92f',
        name: 'patlayan kafa',
        keywords: ['aklını başından almak', 'şaşırmış', 'şok olmuş', 'şoke', 'surat'],
      },
      {
        emoji: '🤠',
        code: '1f920',
        name: 'kovboy şapkalı yüz',
        keywords: ['kadın kovboy', 'kovboy', 'kovboy şapkası yüzü', 'şapka', 'yüz'],
      },
      {
        emoji: '🥳',
        code: '1f973',
        name: 'partide eğlenen yüz',
        keywords: ['doğum günü', 'eğlence', 'iyi ki doğdun', 'konfeti', 'kutlama', 'mutlu yıllar'],
      },
      {
        emoji: '🥸',
        code: '1f978',
        name: 'gizlenmiş yüz',
        keywords: ['ajan', 'bıyık', 'burun', 'casus', 'gözlük', 'kimliğini gizlemek'],
      },
      {
        emoji: '😎',
        code: '1f60e',
        name: 'güneş gözlüklü gülümseme',
        keywords: [
          'cool',
          'gülümseme',
          'güneş gözlüğü',
          'güneş gözlükleri',
          'güneş gözlükleriyle gülümseme',
          'havalı',
        ],
      },
      {
        emoji: '🤓',
        code: '1f913',
        name: 'ukala yüz',
        keywords: ['akıllı', 'bilgili', 'bilmiş', 'çalışkan', 'gözlük', 'gözlüklü'],
      },
      {
        emoji: '🧐',
        code: '1f9d0',
        name: 'tek cam gözlüklü yüz',
        keywords: ['havalı', 'kendini beğenmiş', 'klas', 'surat', 'tek cam gözlük', 'varlıklı'],
      },
      {
        emoji: '😕',
        code: '1f615',
        name: 'kafası karışık yüz',
        keywords: ['bilmiyorum', 'emin olmayan', 'kafası karışmış', 'yüz'],
      },
      {
        emoji: '🫤',
        code: '1fae4',
        name: 'yamuk ağızlı yüz',
        keywords: ['eh', 'hayal kırıklığı', 'hüsran', 'ifade', 'kararsız', 'kırgın'],
      },
      {
        emoji: '😟',
        code: '1f61f',
        name: 'endişeli yüz',
        keywords: ['endişeli', 'gergin', 'yüz'],
      },
      {
        emoji: '🙁',
        code: '1f641',
        name: 'biraz asık surat',
        keywords: ['asık surat', 'endişeli', 'yüz'],
      },
      {
        emoji: '😮',
        code: '1f62e',
        name: 'ağzı açık yüz',
        keywords: ['ağız', 'ağzı açık', 'şaşkın', 'şok', 'süpriz', 'yüz'],
      },
      {
        emoji: '😯',
        code: '1f62f',
        name: 'şaşkın yüz',
        keywords: ['şaşırmış', 'şok olmuş', 'yüz'],
      },
      {
        emoji: '😲',
        code: '1f632',
        name: 'afallamış yüz',
        keywords: ['afallamış', 'şaşkın', 'şoke olmuş', 'tamamen şoke olmuş', 'yüz'],
      },
      {
        emoji: '😳',
        code: '1f633',
        name: 'kızarmış ve şaşkın yüz',
        keywords: ['kızarmış', 'şaşırmış', 'şaşkınlık içinde', 'şok', 'tuhaf', 'yüz'],
      },
      {
        emoji: '🥺',
        code: '1f97a',
        name: 'yalvaran yüz',
        keywords: [
          'acıklı bakışlar',
          'af dilemek',
          'gözleri dolmak',
          'koca göz',
          'lütfen',
          'merhamet',
        ],
      },
      {
        emoji: '🥹',
        code: '1f979',
        name: 'gözleri dolmuş yüz',
        keywords: ['ağlamaklı', 'direnme', 'duygusal', 'gözyaşı', 'gurur', 'ifade'],
      },
      {
        emoji: '😦',
        code: '1f626',
        name: 'hoşnutsuz yüz',
        keywords: [
          'açık ağızlı hoşnutsuz yüz',
          'ağzı açık',
          'boş bulunmuş',
          'hoşnutsuz',
          'korkmuş',
          'yüz',
        ],
      },
      {
        emoji: '😧',
        code: '1f627',
        name: 'kederli yüz',
        keywords: ['acı çeken', 'kederli', 'mutsuz', 'şaşkın', 'yüz'],
      },
      {
        emoji: '😨',
        code: '1f628',
        name: 'korkulu yüz',
        keywords: ['endişeli', 'korkmuş', 'korkulu', 'yüz'],
      },
      {
        emoji: '😰',
        code: '1f630',
        name: 'terli ve endişeli yüz',
        keywords: [
          'açık ağız',
          'endişeli',
          'korkmuş',
          'korkulu yüz',
          'soğuk ter',
          'soğuk ter döken mavi yüz',
        ],
      },
      {
        emoji: '😥',
        code: '1f625',
        name: 'üzgün ama rahatlamış yüz',
        keywords: [
          'canı sıkkın',
          'canı sıkkın ama rahatlamış',
          'endişeli',
          'kafası karışmış',
          'karışık',
          'rahatlamış',
        ],
      },
      {
        emoji: '😢',
        code: '1f622',
        name: 'ağlayan yüz',
        keywords: ['ağlama', 'gözyaşları', 'mutsuz', 'üzgün', 'üzüntülü', 'yüz'],
      },
      {
        emoji: '😭',
        code: '1f62d',
        name: 'avaz avaz ağlayan yüz',
        keywords: ['ağlama', 'avaz avaz ağlama', 'gözyaşları', 'mutsuz', 'üzgün', 'yüz'],
      },
      {
        emoji: '😱',
        code: '1f631',
        name: 'korkuyla çığlık atan yüz',
        keywords: [
          'korkmuş',
          'korku',
          'korku içinde bağıran yüz',
          'korkunç',
          'korkuyla haykıran yüz',
          'yüz',
        ],
      },
      {
        emoji: '😖',
        code: '1f616',
        name: 'kafası çok karışık yüz',
        keywords: ['kafası çok karışmış', 'kızgın', 'pişman', 'yüz'],
      },
      {
        emoji: '😣',
        code: '1f623',
        name: 'kararlı yüz',
        keywords: ['baş ağrısı', 'dayanıklı', 'dikkatli', 'inatçı', 'kararlı', 'konsantre olmuş'],
      },
      {
        emoji: '😞',
        code: '1f61e',
        name: 'memnuniyetsiz yüz',
        keywords: ['kırgın', 'kırgınlık', 'mutsuz', 'umutsuz', 'yüz'],
      },
      {
        emoji: '😓',
        code: '1f613',
        name: 'soğuk ter',
        keywords: ['baş ağrısı', 'endişeli', 'soğuk terli yüz', 'yüz'],
      },
      {
        emoji: '😩',
        code: '1f629',
        name: 'çok yorgun',
        keywords: ['acıkmış', 'hayır', 'olamaz', 'pişman', 'uykulu', 'yorgun yüz'],
      },
      {
        emoji: '😫',
        code: '1f62b',
        name: 'yorgun yüz',
        keywords: ['hapşuran yüz', 'perişan', 'pişman', 'üzgün', 'yorgun', 'yüz'],
      },
      {
        emoji: '🥱',
        code: '1f971',
        name: 'esneyen yüz',
        keywords: ['esneme', 'iyi geceler', 'iyi uykular', 'sıkıcı', 'sıkılmış', 'uykulu'],
      },
      {
        emoji: '😤',
        code: '1f624',
        name: 'burnundan soluyan yüz',
        keywords: [
          'ben kazandım',
          'ben kazandım yüzü',
          'burnundan soluyan',
          'kızgın',
          'mutsuz',
          'sinirli',
        ],
      },
      {
        emoji: '😡',
        code: '1f621',
        name: 'somurtkan yüz',
        keywords: [
          'deli gibi',
          'kırmızı somurtkan yüz',
          'kırmızı yüz',
          'öfkeli',
          'somurtkan',
          'yüz',
        ],
      },
      {
        emoji: '😠',
        code: '1f620',
        name: 'öfkeli yüz',
        keywords: ['deli gibi', 'kızgın', 'mutsuz', 'öfkeli', 'yüz'],
      },
      {
        emoji: '🤬',
        code: '1f92c',
        name: 'ağzında semboller olan yüz',
        keywords: ['kızgın', 'kızmış', 'küfür eden', 'küfür etmek', 'sembol surat', 'sensör'],
      },
      {
        emoji: '😈',
        code: '1f608',
        name: 'boynuzlu gülen yüz',
        keywords: ['boynuzlar', 'boynuzlu gülümseme', 'gülümseme', 'şeytani gülümseme', 'yüz'],
      },
      {
        emoji: '💀',
        code: '1f480',
        name: 'kafatası',
        keywords: ['cadılar bayramı', 'canavar', 'iskelet', 'masal', 'ölüm', 'yüz'],
      },
      {
        emoji: '💩',
        code: '1f4a9',
        name: 'kaka',
        keywords: ['kaka yığını', 'leş', 'pislik', 'yığın'],
      },
      {
        emoji: '🤡',
        code: '1f921',
        name: 'palyaço yüzü',
        keywords: ['palyaço', 'yüz'],
      },
      {
        emoji: '👻',
        code: '1f47b',
        name: 'hayalet',
        keywords: ['cadılar bayramı', 'öcü', 'peri masalı', 'yüz'],
      },
      {
        emoji: '👽',
        code: '1f47d',
        name: 'uzaylı',
        keywords: ['dünya dışı', 'fantastik', 'peri masalı', 'UFO', 'yabancı', 'yaratık'],
      },
      {
        emoji: '🤖',
        code: '1f916',
        name: 'robot',
        keywords: ['canavar', 'yüz'],
      },
      {
        emoji: '😺',
        code: '1f63a',
        name: 'sırıtan kedi',
        keywords: [
          'açık',
          'ağız',
          'gülümseme',
          'gülümseyen kedi yüzü',
          'gülümseyen ve ağzı açık kedi yüzü',
          'kedi',
        ],
      },
      {
        emoji: '😹',
        code: '1f639',
        name: 'sevinç gözyaşları döken kedi',
        keywords: [
          'göz yaşı',
          'gülen kedi',
          'kahkaha atan kedi',
          'kedi',
          'kedi yüzü',
          'komik kedi',
        ],
      },
      {
        emoji: '😻',
        code: '1f63b',
        name: 'kalp gözlü gülümseyen kedi',
        keywords: [
          'aşık',
          'aşk',
          'gözler',
          'gülümseme',
          'gülümseyen ve kalp şeklinde gözleri olan kedi yüzü',
          'kalp',
        ],
      },
      {
        emoji: '😿',
        code: '1f63f',
        name: 'ağlayan kedi',
        keywords: ['ağlama', 'ağlayan kedi yüzü', 'göz yaşı', 'kedi', 'kedi yüzü', 'üzgün'],
      },
    ],
  },
  {
    id: 'gestures',
    name: 'Hareketler',
    emojis: [
      {
        emoji: '👍',
        code: '1f44d',
        name: 'baş parmak yukarıda',
        keywords: ['+1', 'anlaştık', 'beğendim', 'bence de', 'el', 'iyi'],
      },
      {
        emoji: '👎',
        code: '1f44e',
        name: 'baş parmak aşağıda',
        keywords: ['aşağı', 'baş parmak', 'el', 'işaret'],
      },
      {
        emoji: '👏',
        code: '1f44f',
        name: 'el çırpma',
        keywords: ['alkış', 'bravo', 'çırpma', 'el', 'eller', 'işaret'],
      },
      {
        emoji: '🙌',
        code: '1f64c',
        name: 'eller havaya',
        keywords: [
          'çak',
          'her iki el',
          'kutlama',
          'kutlamak için iki eli birden kaldırma',
          'tebrikler',
        ],
      },
      {
        emoji: '🙏',
        code: '1f64f',
        name: 'birleşen eller',
        keywords: ['dua', 'dua etme', 'el', 'hareket'],
      },
      {
        emoji: '💪',
        code: '1f4aa',
        name: 'pazı',
        keywords: ['çizgi roman', 'esnek', 'güçlü', 'kas', 'kas esnetme', 'vücutcu'],
      },
      {
        emoji: '👋',
        code: '1f44b',
        name: 'el sallama',
        keywords: ['bay bay', 'bye', 'el', 'görüşürüz', 'güle güle', 'hey'],
      },
      {
        emoji: '✌️',
        code: '270c',
        name: 'zafer işareti',
        keywords: ['barış', 'el', 'oleey', 'zafer', 'zafer eli'],
      },
      {
        emoji: '🤞',
        code: '1f91e',
        name: 'şans dileme',
        keywords: ['çapraz', 'el', 'parmak', 'şans', 'söz verme'],
      },
      {
        emoji: '🤟',
        code: '1f91f',
        name: 'seni seviyorum işareti',
        keywords: ['el', 'seni seviyorum', 'SS'],
      },
      {
        emoji: '👌',
        code: '1f44c',
        name: 'tamam işareti',
        keywords: ['anlaştık', 'el', 'harika', 'işaret', 'işte bu', 'mükemmel'],
      },
      {
        emoji: '🫶',
        code: '1faf6',
        name: 'kalp oluşturan eller',
        keywords: ['<3', 'aşk', 'birlikte', 'biz', 'el', 'kalp'],
      },
      {
        emoji: '🤝',
        code: '1f91d',
        name: 'el sıkışma',
        keywords: ['anlaşma', 'el', 'sallama', 'toplantı'],
      },
      {
        emoji: '✍️',
        code: '270d',
        name: 'yazı yazan el',
        keywords: ['beden', 'el', 'kalem tutma', 'yazma'],
      },
      {
        emoji: '🧠',
        code: '1f9e0',
        name: 'beyin',
        keywords: ['akıllı', 'zeka', 'zeki'],
      },
      {
        emoji: '👀',
        code: '1f440',
        name: 'gözler',
        keywords: ['bakmak', 'görmek', 'gözcü', 'gözetlemek', 'yüz'],
      },
    ],
  },
  {
    id: 'symbols',
    name: 'Kalpler & Semboller',
    emojis: [
      {
        emoji: '❤️',
        code: '2764',
        name: 'kırmızı kalp',
        keywords: ['aşk', 'kalp'],
      },
      {
        emoji: '🧡',
        code: '1f9e1',
        name: 'turuncu kalp',
        keywords: ['kalp', 'portakal', 'turuncu'],
      },
      {
        emoji: '💛',
        code: '1f49b',
        name: 'sarı kalp',
        keywords: ['duygu', 'kalp', 'sarı'],
      },
      {
        emoji: '💚',
        code: '1f49a',
        name: 'yeşil kalp',
        keywords: ['duygu', 'kalp', 'yeşil'],
      },
      {
        emoji: '💙',
        code: '1f499',
        name: 'mavi kalp',
        keywords: ['duygu', 'kalp', 'mavi'],
      },
      {
        emoji: '💜',
        code: '1f49c',
        name: 'mor kalp',
        keywords: ['duygu', 'kalp', 'mor'],
      },
      {
        emoji: '🖤',
        code: '1f5a4',
        name: 'siyah kalp',
        keywords: ['fena', 'kalp', 'kötü', 'siyah'],
      },
      {
        emoji: '🤍',
        code: '1f90d',
        name: 'beyaz kalp',
        keywords: ['beyaz', 'kalp'],
      },
      {
        emoji: '🤎',
        code: '1f90e',
        name: 'kahverengi kalp',
        keywords: ['kahverengi', 'kalp'],
      },
      {
        emoji: '💔',
        code: '1f494',
        name: 'kırık kalp',
        keywords: ['duygu', 'hüsran', 'kalp', 'kırılmış', 'kırma'],
      },
      {
        emoji: '❤️‍🔥',
        code: '2764-200d-1f525',
        name: 'ateşli kalp',
        keywords: ['alev', 'arzu', 'aşk', 'kalp', 'kutsal kalp', 'tutku'],
      },
      {
        emoji: '💕',
        code: '1f495',
        name: 'iki kalp',
        keywords: ['aşıklar', 'aşk', 'duygu', 'evlilik yıldönümü', 'seni seviyorum', 'sevgili'],
      },
      {
        emoji: '💖',
        code: '1f496',
        name: 'pırıldayan kalp',
        keywords: ['duygu', 'heyecanlı', 'kalp', 'pembe kalp', 'pırıldayan'],
      },
      {
        emoji: '💯',
        code: '1f4af',
        name: 'yüz puan',
        keywords: ['100', '100 puan', 'skor', 'yuz'],
      },
      {
        emoji: '✨',
        code: '2728',
        name: 'parıltılar',
        keywords: [
          '*',
          'mucize',
          'parıldayan yıldızlar',
          'parıltı',
          'pırıldayan yıldızlar',
          'pırıltı',
        ],
      },
      {
        emoji: '⭐',
        code: '2b50',
        name: 'yıldız',
        keywords: ['beyaz orta yıldız', 'gece', 'gökyüzü', 'kutup yıldızı'],
      },
      {
        emoji: '🌟',
        code: '1f31f',
        name: 'parıldayan yıldız',
        keywords: ['dilek', 'dilek yıldızı', 'kıvılcım', 'kutup yıldızı', 'parıldama', 'parlak'],
      },
      {
        emoji: '💫',
        code: '1f4ab',
        name: 'baş dönmesi',
        keywords: ['çizgi roman', 'dilek', 'duygu', 'gece', 'gökyüzü', 'kayan yıldız'],
      },
      {
        emoji: '🔥',
        code: '1f525',
        name: 'ateş',
        keywords: ['alev', 'sıcak', 'yakmak'],
      },
      {
        emoji: '⚡',
        code: '26a1',
        name: 'yüksek voltaj',
        keywords: ['doğa', 'elektrik', 'fırtına', 'işaret', 'şimşek', 'tehlike'],
      },
      {
        emoji: '💥',
        code: '1f4a5',
        name: 'çarpışma',
        keywords: ['bomba', 'bum', 'çarpışma işareti', 'çizgi roman', 'duygu', 'patlama'],
      },
      {
        emoji: '💤',
        code: '1f4a4',
        name: 'zzz',
        keywords: ['çizgi roman', 'gece', 'iyi geceler', 'iyi uykular', 'uyku', 'uyuklama'],
      },
      {
        emoji: '💬',
        code: '1f4ac',
        name: 'konuşma balonu',
        keywords: ['balon', 'çizgi roman', 'iletişim', 'iletişim balonu'],
      },
      {
        emoji: '💭',
        code: '1f4ad',
        name: 'düşünce balonu',
        keywords: ['balon', 'bulut', 'çizgi roman', 'düşünce', 'fikir'],
      },
      {
        emoji: '✅',
        code: '2705',
        name: 'onay işareti düğmesi',
        keywords: ['✓', 'düğme', 'işaret', 'kalın onay işareti', 'onay', 'onay işareti'],
      },
      {
        emoji: '❌',
        code: '274c',
        name: 'çarpı işareti',
        keywords: ['×', 'çarpı', 'çarpma', 'iptal', 'işaret', 'x'],
      },
      {
        emoji: '⛔',
        code: '26d4',
        name: 'girilmez',
        keywords: ['girilmez işareti', 'hayır', 'işaret', 'yasak'],
      },
      {
        emoji: '⚠️',
        code: '26a0',
        name: 'uyarı işareti',
        keywords: ['dikkat', 'işaret', 'uyarı'],
      },
      {
        emoji: '🚫',
        code: '1f6ab',
        name: 'girmek yasak',
        keywords: ['Girilmez', 'işaret'],
      },
      {
        emoji: '❓',
        code: '2753',
        name: 'kırmızı soru işareti',
        keywords: ['?', 'işaret', 'noktalama', 'soru', 'soru işareti'],
      },
      {
        emoji: '❗',
        code: '2757',
        name: 'kırmızı ünlem işareti',
        keywords: ['!', 'işaret', 'noktalama', 'ünlem', 'ünlem işareti'],
      },
      {
        emoji: '🟢',
        code: '1f7e2',
        name: 'yeşil daire',
        keywords: ['daire', 'yeşil'],
      },
      {
        emoji: '🟡',
        code: '1f7e1',
        name: 'sarı daire',
        keywords: ['daire', 'sarı'],
      },
      {
        emoji: '🔴',
        code: '1f534',
        name: 'kırmızı daire',
        keywords: ['büyük kırmızı çember', 'çember', 'kırmızı'],
      },
      {
        emoji: '🔵',
        code: '1f535',
        name: 'mavi daire',
        keywords: ['büyük mavi çember', 'çember', 'mavi'],
      },
      {
        emoji: '🟣',
        code: '1f7e3',
        name: 'mor daire',
        keywords: ['daire', 'mor'],
      },
      {
        emoji: '⚪',
        code: '26aa',
        name: 'beyaz daire',
        keywords: ['daire', 'geometri'],
      },
      {
        emoji: '🎉',
        code: '1f389',
        name: 'parti konfetisi',
        keywords: ['harika', 'konfeti', 'kutlama', 'parti', 'tebrikler'],
      },
      {
        emoji: '🎊',
        code: '1f38a',
        name: 'konfeti',
        keywords: ['konfeti topu', 'kutlama', 'top'],
      },
    ],
  },
  {
    id: 'activities',
    name: 'Aktivite & Spor',
    emojis: [
      {
        emoji: '🏃',
        code: '1f3c3',
        name: 'koşan kişi',
        keywords: ['acele', 'çabuk', 'hızlı', 'kişi', 'koşu', 'koşucu'],
      },
      {
        emoji: '🚶',
        code: '1f6b6',
        name: 'yürüyen kişi',
        keywords: ['aylak', 'gezinti', 'kişi', 'salınma', 'tempo', 'vücut'],
      },
      {
        emoji: '🧘',
        code: '1f9d8',
        name: 'lotus pozisyonundaki kişi',
        keywords: ['bağdaş kurmak', 'lotus pozisyonu', 'meditasyon', 'rahatlamak', 'yoga'],
      },
      {
        emoji: '🏋️',
        code: '1f3cb',
        name: 'ağırlık kaldıran kişi',
        keywords: [
          'ağırlık',
          'ağırlık kaldırma',
          'antrenman',
          'erkek halterci',
          'halter',
          'halterci',
        ],
      },
      {
        emoji: '🚴',
        code: '1f6b4',
        name: 'bisiklet süren kişi',
        keywords: ['antrenman', 'bisiklet', 'bisiklet sürücüsü', 'bisikletçi', 'hareket', 'kişi'],
      },
      {
        emoji: '🏊',
        code: '1f3ca',
        name: 'yüzen kişi',
        keywords: ['antrenman', 'hareket', 'havuz', 'kişi', 'serbest stil', 'spor'],
      },
      {
        emoji: '⚽',
        code: '26bd',
        name: 'futbol topu',
        keywords: ['futbol', 'spor', 'top', 'topu'],
      },
      {
        emoji: '🏀',
        code: '1f3c0',
        name: 'basketbol',
        keywords: ['basketbol potası', 'basketbol topu', 'pota', 'spor', 'top'],
      },
      {
        emoji: '🎾',
        code: '1f3be',
        name: 'tenis',
        keywords: ['spor', 'tenis raketi ve topu', 'tenis topu', 'top'],
      },
      {
        emoji: '🏐',
        code: '1f3d0',
        name: 'voleybol',
        keywords: ['maç', 'top', 'voleybol topu'],
      },
      {
        emoji: '🎮',
        code: '1f3ae',
        name: 'video oyunu',
        keywords: ['kontrol cihazı', 'oyun', 'oyun konsolu', 'oyun kontrol cihazı', 'xbox'],
      },
      {
        emoji: '🎲',
        code: '1f3b2',
        name: 'oyun zarı',
        keywords: ['oyun', 'tavla', 'zar'],
      },
      {
        emoji: '🧩',
        code: '1f9e9',
        name: 'yapboz parçası',
        keywords: ['bulmaca', 'ipucu', 'karmaşık', 'kenetleme', 'oyun', 'parça'],
      },
      {
        emoji: '🎯',
        code: '1f3af',
        name: 'tam isabet',
        keywords: ['hedef', 'hedefe isabet', 'isabet', 'on ikiden vurma', 'oyun'],
      },
      {
        emoji: '🎨',
        code: '1f3a8',
        name: 'boya paleti',
        keywords: ['boya', 'palet', 'ressam', 'sanat', 'sanatçı', 'sanatçı paleti'],
      },
      {
        emoji: '🎬',
        code: '1f3ac',
        name: 'film tahtası',
        keywords: ['eğlence', 'film', 'tahta'],
      },
      {
        emoji: '🎤',
        code: '1f3a4',
        name: 'mikrofon',
        keywords: ['eğlence', 'Karaoke', 'müzik', 'şarkı', 'şarkıcı'],
      },
      {
        emoji: '🎧',
        code: '1f3a7',
        name: 'kulaklık',
        keywords: ['eğlence', 'müzik'],
      },
      {
        emoji: '🎵',
        code: '1f3b5',
        name: 'müzik notası',
        keywords: ['müzik', 'nota'],
      },
      {
        emoji: '🎸',
        code: '1f3b8',
        name: 'gitar',
        keywords: ['alet', 'elektrik gitar', 'müzik', 'müzik aleti'],
      },
      {
        emoji: '🎹',
        code: '1f3b9',
        name: 'müzik klavyesi',
        keywords: ['alet', 'klavye', 'müzik', 'müzik aleti', 'piyano'],
      },
      {
        emoji: '📸',
        code: '1f4f8',
        name: 'flaşlı fotoğraf makinesi',
        keywords: ['flaş', 'kamera', 'video'],
      },
      {
        emoji: '🛍️',
        code: '1f6cd',
        name: 'alışveriş çantası',
        keywords: ['alışveriş', 'çanta', 'hediye', 'otel', 'paket'],
      },
      {
        emoji: '💃',
        code: '1f483',
        name: 'dans eden kadın',
        keywords: ['dans', 'dansçı', 'festival', 'kadın dansçı', 'kişiler', 'meslek'],
      },
      {
        emoji: '🕺',
        code: '1f57a',
        name: 'dans eden adam',
        keywords: ['adam', 'dans', 'meslek'],
      },
      {
        emoji: '🎳',
        code: '1f3b3',
        name: 'bovling',
        keywords: ['bovling ekipmanı', 'bovling topu', 'oyun', 'top'],
      },
      {
        emoji: '⛳',
        code: '26f3',
        name: 'delikteki bayrak',
        keywords: ['delik', 'golf', 'golf bayrağı'],
      },
      {
        emoji: '🏓',
        code: '1f3d3',
        name: 'masa tenisi',
        keywords: ['maç', 'pinpon', 'raket', 'top'],
      },
      {
        emoji: '🥊',
        code: '1f94a',
        name: 'boks eldiveni',
        keywords: ['boks', 'eldiven', 'spor'],
      },
    ],
  },
  {
    id: 'food',
    name: 'Yiyecek & İçecek',
    emojis: [
      {
        emoji: '☕',
        code: '2615',
        name: 'sıcak içecek',
        keywords: ['çay', 'dumanı tüten', 'içecek', 'kahve', 'sıcak'],
      },
      {
        emoji: '🍵',
        code: '1f375',
        name: 'çay fincanı',
        keywords: ['çay', 'içecek', 'yeşil çay'],
      },
      {
        emoji: '🧋',
        code: '1f9cb',
        name: 'bubble tea',
        keywords: ['baloncuk', 'boba', 'çay', 'içecek', 'inci', 'inci çayı'],
      },
      {
        emoji: '🥤',
        code: '1f964',
        name: 'pipetli bardak',
        keywords: ['ayran', 'gazoz', 'içecek', 'kamışlı bardak', 'kola', 'plastik bardak'],
      },
      {
        emoji: '🍺',
        code: '1f37a',
        name: 'bira kupası',
        keywords: ['bar', 'kupa', 'restoran'],
      },
      {
        emoji: '🍻',
        code: '1f37b',
        name: 'bira kupaları tokuşturma',
        keywords: ['bar', 'bira', 'içki', 'kupa', 'kupalar', 'restoran'],
      },
      {
        emoji: '🍷',
        code: '1f377',
        name: 'şarap kadehi',
        keywords: ['bar', 'bardak', 'bardak şarap', 'içecek', 'içedek', 'kadeh'],
      },
      {
        emoji: '🥂',
        code: '1f942',
        name: 'kadeh tokuşturma',
        keywords: ['bardak', 'içecek', 'kutlama', 'şampanya', 'tokuşturma'],
      },
      {
        emoji: '🍹',
        code: '1f379',
        name: 'tropik içecek',
        keywords: ['bar', 'içecek', 'kokteyl', 'restoran', 'tropik'],
      },
      {
        emoji: '🍕',
        code: '1f355',
        name: 'pizza dilimi',
        keywords: ['dilim', 'gıda', 'peynirli pizza', 'pizza', 'restoran', 'yiyecek'],
      },
      {
        emoji: '🍔',
        code: '1f354',
        name: 'hamburger',
        keywords: ['çizburger', 'gıda', 'restoran', 'yemek', 'yiyecek'],
      },
      {
        emoji: '🍟',
        code: '1f35f',
        name: 'patates kızartması',
        keywords: ['gıda', 'kızartma patates', 'McDonald’s', 'restoran'],
      },
      {
        emoji: '🌭',
        code: '1f32d',
        name: 'sosisli sandviç',
        keywords: ['gıda', 'hot dog', 'sosis'],
      },
      {
        emoji: '🌮',
        code: '1f32e',
        name: 'tako',
        keywords: ['gıda', 'meksika sandviçi', 'Meksika sandviçi'],
      },
      {
        emoji: '🥙',
        code: '1f959',
        name: 'dürüm',
        keywords: ['döner', 'ekmek arası', 'falafel', 'gıda', 'kebap', 'pide'],
      },
      {
        emoji: '🍝',
        code: '1f35d',
        name: 'spagetti',
        keywords: ['gıda', 'makarna', 'restoran', 'yemek'],
      },
      {
        emoji: '🍜',
        code: '1f35c',
        name: 'erişte',
        keywords: ['buharda pişmiş', 'gıda', 'makarna', 'noodle', 'noodle tabağı', 'restoran'],
      },
      {
        emoji: '🍣',
        code: '1f363',
        name: 'suşi',
        keywords: ['çiğ balık', 'gıda', 'japon', 'restoran', 'sushi', 'suşi nigiri'],
      },
      {
        emoji: '🍱',
        code: '1f371',
        name: 'bento',
        keywords: ['bento paketi', 'gıda', 'paket', 'restoran', 'sushi', 'yemek'],
      },
      {
        emoji: '🍳',
        code: '1f373',
        name: 'yemek pişirme',
        keywords: ['gıda', 'kahvaltı', 'kızartma tavası', 'pişirme', 'restoran', 'sahanda yumurta'],
      },
      {
        emoji: '🥐',
        code: '1f950',
        name: 'kruvasan',
        keywords: ['ay çöreği', 'ekmek', 'fransız', 'gıda', 'pastane', 'yiyecek'],
      },
      {
        emoji: '🥗',
        code: '1f957',
        name: 'yeşil salata',
        keywords: ['gıda', 'sağlıklı', 'salata', 'yemek', 'yeşil', 'yiyecek'],
      },
      {
        emoji: '🍎',
        code: '1f34e',
        name: 'kırmızı elma',
        keywords: ['elma', 'gıda', 'kırmızı', 'meyve'],
      },
      {
        emoji: '🍓',
        code: '1f353',
        name: 'çilek',
        keywords: ['gıda', 'meyve', 'yumuşak meyve'],
      },
      {
        emoji: '🍉',
        code: '1f349',
        name: 'karpuz',
        keywords: ['gıda', 'meyve'],
      },
      {
        emoji: '🍌',
        code: '1f34c',
        name: 'muz',
        keywords: ['gıda', 'maymun', 'meyve'],
      },
      {
        emoji: '🍩',
        code: '1f369',
        name: 'donut',
        keywords: ['çikolatalı donut', 'çikolatalı lokma', 'donat', 'doughnut', 'gıda', 'restoran'],
      },
      {
        emoji: '🍪',
        code: '1f36a',
        name: 'kurabiye',
        keywords: ['çikolatalı kurabiye', 'cookie', 'gıda', 'restoran'],
      },
      {
        emoji: '🎂',
        code: '1f382',
        name: 'doğum günü pastası',
        keywords: ['dilek', 'doğum günü', 'gıda', 'iyi ki doğdun', 'kek', 'krema'],
      },
      {
        emoji: '🍰',
        code: '1f370',
        name: 'pasta dilimi',
        keywords: ['dilim pasta', 'doğum günü', 'gıda', 'pasta', 'restoran'],
      },
      {
        emoji: '🍫',
        code: '1f36b',
        name: 'çikolata',
        keywords: ['bar', 'çikolata barı', 'gıda', 'restoran', 'tatlı'],
      },
      {
        emoji: '🍿',
        code: '1f37f',
        name: 'patlamış mısır',
        keywords: ['gıda', 'mısır', 'sinema'],
      },
      {
        emoji: '🍦',
        code: '1f366',
        name: 'yumuşak dondurma',
        keywords: ['dondurma', 'dondurma külahı', 'gıda', 'krema', 'külah', 'restoran'],
      },
    ],
  },
  {
    id: 'travel',
    name: 'Seyahat & Yerler',
    emojis: [
      {
        emoji: '🚗',
        code: '1f697',
        name: 'araba',
        keywords: ['araç', 'otomobil', 'taşıt'],
      },
      {
        emoji: '🚕',
        code: '1f695',
        name: 'taksi',
        keywords: ['araba', 'sarı taksi', 'taşıt'],
      },
      {
        emoji: '🚌',
        code: '1f68c',
        name: 'otobüs',
        keywords: ['minibüs', 'taşıt', 'toplu taşıma'],
      },
      {
        emoji: '🚇',
        code: '1f687',
        name: 'metro',
        keywords: ['marmaray', 'taşıt', 'toplu taşıma', 'tren', 'ulaşım'],
      },
      {
        emoji: '🚆',
        code: '1f686',
        name: 'tren',
        keywords: ['demiryolu', 'taşıt'],
      },
      {
        emoji: '✈️',
        code: '2708',
        name: 'uçak',
        keywords: ['jet', 'seyahat', 'taşıt', 'uçmak', 'yolculuk'],
      },
      {
        emoji: '🚀',
        code: '1f680',
        name: 'roket',
        keywords: ['çıkış', 'taşıt', 'uzay', 'yolculuk'],
      },
      {
        emoji: '🚲',
        code: '1f6b2',
        name: 'bisiklet',
        keywords: ['bisiklete binmek', 'cycling', 'sürüş', 'taşıt'],
      },
      {
        emoji: '🛵',
        code: '1f6f5',
        name: 'motorlu skuter',
        keywords: ['motor', 'skuter'],
      },
      {
        emoji: '🛳️',
        code: '1f6f3',
        name: 'yolcu gemisi',
        keywords: ['gemi', 'motor', 'taşıt', 'tekne', 'vapur', 'yolcu'],
      },
      {
        emoji: '⛵',
        code: '26f5',
        name: 'yelkenli tekne',
        keywords: ['deniz tatil yeri', 'deniz tatili', 'tatil yeri', 'tekne', 'yat'],
      },
      {
        emoji: '🏠',
        code: '1f3e0',
        name: 'ev',
        keywords: ['bina', 'konut', 'yuva'],
      },
      {
        emoji: '🏢',
        code: '1f3e2',
        name: 'ofis binası',
        keywords: ['belediye', 'bina', 'devlet dairesi', 'ofis'],
      },
      {
        emoji: '🏫',
        code: '1f3eb',
        name: 'okul',
        keywords: ['bina', 'ilkokul', 'lise', 'okul binası'],
      },
      {
        emoji: '🏥',
        code: '1f3e5',
        name: 'hastane',
        keywords: ['bina', 'klinik', 'sağlık ocağı'],
      },
      {
        emoji: '🏖️',
        code: '1f3d6',
        name: 'plaj ve şemsiye',
        keywords: ['ada', 'kumsal', 'plaj', 'şemsiye', 'tatil'],
      },
      {
        emoji: '🏝️',
        code: '1f3dd',
        name: 'ıssız ada',
        keywords: ['ada', 'çöl'],
      },
      {
        emoji: '⛰️',
        code: '26f0',
        name: 'dağ',
        keywords: [],
      },
      {
        emoji: '🏕️',
        code: '1f3d5',
        name: 'kamp',
        keywords: ['kamp yapma'],
      },
      {
        emoji: '🌃',
        code: '1f303',
        name: 'yıldızlı gece',
        keywords: ['gece', 'şehir', 'yıldızlar'],
      },
      {
        emoji: '🗺️',
        code: '1f5fa',
        name: 'dünya haritası',
        keywords: ['dünya', 'harita'],
      },
      {
        emoji: '🧳',
        code: '1f9f3',
        name: 'bavul',
        keywords: ['bagaj', 'çanta', 'seyahat', 'tatil', 'valiz', 'yol'],
      },
      {
        emoji: '🏨',
        code: '1f3e8',
        name: 'otel',
        keywords: ['bina', 'kalacak yer'],
      },
      {
        emoji: '⛽',
        code: '26fd',
        name: 'akaryakıt istasyonu',
        keywords: ['benzin', 'benzin istasyonu', 'benzinci', 'gaz', 'istasyon', 'pompa'],
      },
    ],
  },
  {
    id: 'objects',
    name: 'Nesneler & İş',
    emojis: [
      {
        emoji: '💼',
        code: '1f4bc',
        name: 'evrak çantası',
        keywords: ['müfettiş', 'ofis'],
      },
      {
        emoji: '💻',
        code: '1f4bb',
        name: 'dizüstü bilgisayar',
        keywords: ['bilgisayar', 'kişisel'],
      },
      {
        emoji: '🖥️',
        code: '1f5a5',
        name: 'masaüstü bilgisayar',
        keywords: ['bilgisayar', 'masaüstü'],
      },
      {
        emoji: '📱',
        code: '1f4f1',
        name: 'cep telefonu',
        keywords: ['iPhone', 'mobil telefon', 'telefon'],
      },
      {
        emoji: '⌨️',
        code: '2328',
        name: 'klavye',
        keywords: ['bilgisayar'],
      },
      {
        emoji: '📚',
        code: '1f4da',
        name: 'kitaplar',
        keywords: ['kitap'],
      },
      {
        emoji: '📖',
        code: '1f4d6',
        name: 'açık kitap',
        keywords: ['açık defter', 'defter', 'kitap', 'okul'],
      },
      {
        emoji: '📝',
        code: '1f4dd',
        name: 'not',
        keywords: ['ders', 'iletişim', 'kalem', 'kalem kağıt', 'not defteri'],
      },
      {
        emoji: '✏️',
        code: '270f',
        name: 'kurşun kalem',
        keywords: [],
      },
      {
        emoji: '📅',
        code: '1f4c5',
        name: 'takvim',
        keywords: ['tarih'],
      },
      {
        emoji: '📆',
        code: '1f4c6',
        name: 'koparmalı takvim',
        keywords: ['takvim', 'takvim sayfası', 'tarih'],
      },
      {
        emoji: '🗓️',
        code: '1f5d3',
        name: 'spiral takvim',
        keywords: ['defter', 'spiral', 'takvim'],
      },
      {
        emoji: '⏰',
        code: '23f0',
        name: 'çalar saat',
        keywords: ['alarm', 'saat'],
      },
      {
        emoji: '⌛',
        code: '231b',
        name: 'kum saati',
        keywords: ['kum'],
      },
      {
        emoji: '📌',
        code: '1f4cc',
        name: 'raptiye',
        keywords: ['iğne'],
      },
      {
        emoji: '📎',
        code: '1f4ce',
        name: 'ataş',
        keywords: ['klips'],
      },
      {
        emoji: '🔑',
        code: '1f511',
        name: 'anahtar',
        keywords: ['kilit', 'parola', 'şifre'],
      },
      {
        emoji: '💡',
        code: '1f4a1',
        name: 'ampul',
        keywords: ['bir fikrim var', 'çizgi roman', 'elektrik', 'ışık'],
      },
      {
        emoji: '🔋',
        code: '1f50b',
        name: 'pil',
        keywords: [],
      },
      {
        emoji: '🔌',
        code: '1f50c',
        name: 'elektrik fişi',
        keywords: ['elektrik'],
      },
      {
        emoji: '🛒',
        code: '1f6d2',
        name: 'alışveriş arabası',
        keywords: ['alışveriş', 'araba', 'pazar arabası'],
      },
      {
        emoji: '🎁',
        code: '1f381',
        name: 'paketlenmiş hediye',
        keywords: ['doğum günü', 'hediye', 'kutlama', 'paketli'],
      },
      {
        emoji: '💊',
        code: '1f48a',
        name: 'hap',
        keywords: ['doktor', 'ilaç'],
      },
      {
        emoji: '🩺',
        code: '1fa7a',
        name: 'stetoskop',
        keywords: ['doktor', 'kalp', 'tıp'],
      },
      {
        emoji: '🧹',
        code: '1f9f9',
        name: 'süpürge',
        keywords: ['büyücü', 'cadı', 'ev işi', 'harry potter', 'süpürme', 'süpürmek'],
      },
      {
        emoji: '🧺',
        code: '1f9fa',
        name: 'sepet',
        keywords: ['çamaşır', 'çamaşır sepeti', 'çiftçilik', 'hasır', 'piknik', 'piknik sepeti'],
      },
      {
        emoji: '🛏️',
        code: '1f6cf',
        name: 'yatak',
        keywords: ['otel', 'uyku', 'uyuma'],
      },
      {
        emoji: '🛁',
        code: '1f6c1',
        name: 'banyo küveti',
        keywords: ['banyo', 'köpük', 'köpüklü banyo'],
      },
      {
        emoji: '📦',
        code: '1f4e6',
        name: 'paket',
        keywords: ['kutu', 'posta'],
      },
      {
        emoji: '✉️',
        code: '2709',
        name: 'zarf',
        keywords: ['e-mail', 'e-posta', 'mektup'],
      },
      {
        emoji: '📞',
        code: '1f4de',
        name: 'ahize',
        keywords: ['alıcı', 'telefon'],
      },
      {
        emoji: '💰',
        code: '1f4b0',
        name: 'para torbası',
        keywords: ['çanta', 'dolar çantası', 'para', 'para çuvalı', 'zengin'],
      },
      {
        emoji: '💳',
        code: '1f4b3',
        name: 'kredi kartı',
        keywords: ['kart', 'kredi'],
      },
      {
        emoji: '🧾',
        code: '1f9fe',
        name: 'makbuz',
        keywords: ['belge', 'defter tutma', 'dekont', 'ekstre', 'evrak', 'fatura'],
      },
    ],
  },
  {
    id: 'nature',
    name: 'Doğa & Hava',
    emojis: [
      {
        emoji: '☀️',
        code: '2600',
        name: 'güneş',
        keywords: ['aydınlık', 'güneşli', 'hava durumu', 'ışık', 'sıcak', 'uzay'],
      },
      {
        emoji: '🌤️',
        code: '1f324',
        name: 'bulutun arkasındaki güneş',
        keywords: ['bulut', 'güneş', 'hava durumu', 'parçalı bulutlu'],
      },
      {
        emoji: '⛅',
        code: '26c5',
        name: 'bulutlar ardındaki güneş',
        keywords: ['bulut', 'bulutlu güneş', 'güneş', 'hava', 'parçalı bulutlu'],
      },
      {
        emoji: '🌧️',
        code: '1f327',
        name: 'yağmur bulutu',
        keywords: ['bulut', 'hava durumu', 'yağmur'],
      },
      {
        emoji: '⛈️',
        code: '26c8',
        name: 'şimşek ve yağmurlu bulut',
        keywords: ['bulut', 'gökgürültüsü', 'hava durumu', 'yağmur'],
      },
      {
        emoji: '❄️',
        code: '2744',
        name: 'kar tanesi',
        keywords: ['buz', 'hava durumu', 'kar', 'kış', 'soğuk'],
      },
      {
        emoji: '☃️',
        code: '2603',
        name: 'kardan adam',
        keywords: ['hava durumu', 'kar', 'kış', 'soğuk'],
      },
      {
        emoji: '🌈',
        code: '1f308',
        name: 'gökkuşağı',
        keywords: ['biseksüel', 'gay', 'hava durumu', 'lezbiyen', 'yağmur'],
      },
      {
        emoji: '🌙',
        code: '1f319',
        name: 'hilal',
        keywords: ['ay', 'dilek', 'gece', 'gökyüzü', 'uzay', 'yeni ay'],
      },
      {
        emoji: '🌊',
        code: '1f30a',
        name: 'dalga',
        keywords: ['okyanus dalgası', 'sörf', 'su dalgası'],
      },
      {
        emoji: '🌸',
        code: '1f338',
        name: 'kiraz çiçeği',
        keywords: ['bahar', 'çiçek', 'çiçek izleme', 'kiraz'],
      },
      {
        emoji: '🌻',
        code: '1f33b',
        name: 'ayçiçeği',
        keywords: ['bitki', 'çiçek', 'güneş'],
      },
      {
        emoji: '🌳',
        code: '1f333',
        name: 'yaprak döken ağaç',
        keywords: ['ağaç', 'orman', 'yaprak döken', 'yeşil ağaç'],
      },
      {
        emoji: '🍀',
        code: '1f340',
        name: 'dört yapraklı yonca',
        keywords: ['bitki', 'dört', 'iskoç', 'şans', 'şanslı', 'yaprak'],
      },
      {
        emoji: '🍂',
        code: '1f342',
        name: 'düşen yapraklar',
        keywords: ['düşen', 'düşmüş', 'güz', 'sonbahar', 'yaprak', 'yapraklar'],
      },
      {
        emoji: '🐶',
        code: '1f436',
        name: 'köpek yüzü',
        keywords: ['hayvan', 'köpek', 'yüz'],
      },
      {
        emoji: '🐱',
        code: '1f431',
        name: 'kedi yüzü',
        keywords: ['ev hayvanı', 'hayvan', 'kedi', 'miyav', 'mındık', 'mırnav'],
      },
      {
        emoji: '🐻',
        code: '1f43b',
        name: 'ayı',
        keywords: ['ayı yüzü', 'hayvan', 'orman', 'yüz'],
      },
      {
        emoji: '🐼',
        code: '1f43c',
        name: 'panda',
        keywords: ['bambu', 'hayvan', 'panda yüzü', 'tembel', 'yüz'],
      },
      {
        emoji: '🦊',
        code: '1f98a',
        name: 'tilki',
        keywords: ['akıllı', 'hayvan', 'kurnaz', 'tilki yüzü', 'yüz'],
      },
      {
        emoji: '🐸',
        code: '1f438',
        name: 'kurbağa',
        keywords: ['hayvan', 'kurbağa yüzü', 'vırak', 'yüz', 'zıp zıp'],
      },
      {
        emoji: '🦋',
        code: '1f98b',
        name: 'kelebek',
        keywords: ['böcek', 'şirin'],
      },
      {
        emoji: '🐝',
        code: '1f41d',
        name: 'bal arısı',
        keywords: ['arı', 'hayvan', 'iğne', 'vız vız'],
      },
      {
        emoji: '🐢',
        code: '1f422',
        name: 'kaplumbağa',
        keywords: ['hayvan'],
      },
    ],
  },
];
